# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '12.0'
workspace 'Hello_Swift.xcworkspace'

#xcodeproj 'SwiftNote_App/SwiftNote_App.xcodeproj'

use_frameworks!

#这段代码的作用是先获取Pods项目（pods_project）中的目标数组（targets），然后遍历目标数组通过目标对象（target）获取构建配置数组（build_configurations），
#最后遍历构建配置数组修改构建配置对象中的构建设置（build_settings），将iOS 部署目标版本设为11.0。
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end


def commonPods
         #UI library
         pod 'SnapKit', :inhibit_warnings => true
         pod 'FilesProvider', :inhibit_warnings => true
         pod 'SwiftyJSON', :inhibit_warnings => true
         pod 'FLAnimatedImage', :inhibit_warnings => true
         pod 'MJRefresh', :inhibit_warnings => true
end

target 'SwiftTest_App' do
  project 'SwiftTest_App/SwiftTest_App.xcodeproj'
  
  # 网络检测
  pod 'Reachability', :inhibit_warnings => true # :inhibit_warnings => true 忽略第三方库的警告
  pod 'Alamofire', :inhibit_warnings => true #网络处理
  #测试自己制作的cocoapod库
  pod 'ctc_podspec', :git =>'https://github.com/chuntiancai/TestCocoapod.git'
#  pod 'CTC_LocalPod', :path => './CTC_LocalPodSpec/CTC_LocalPod', :subspecs => ["GrowingIO"]
  # 测试GrowingIO
  pod 'GrowingAutoTrackKit', :inhibit_warnings => true
  
  # 测试绘制图表第三方库
  pod 'Charts', :inhibit_warnings => true
  
  # 集成bugly，上报bug
  pod 'Bugly', :inhibit_warnings => true
  
  
  
  # 测试图片下载的第三方库
  pod 'SDWebImage','~>5.11.1', :inhibit_warnings => true
  
  #测试日历显示的第三方库
  pod 'FSCalendar','~>2.8.2', :inhibit_warnings => true
  
  #测试滑动标签页
  pod 'JXPagingView/Paging', :inhibit_warnings => true
  
  commonPods
  
end

target 'SwiftNote_App' do
  project 'SwiftNote_App/SwiftNote_App.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#  pod 'CTC_LocalPod' , :path => './CTC_LocalPodSpec/CTC_LocalPod'
  commonPods
  
end

target 'SwiftBluetooth_App' do
  project 'SwiftBluetooth_App/SwiftBluetooth_App.xcodeproj'
#  pod 'CTC_LocalPod', :path => './CTC_LocalPodSpec/CTC_LocalPod', :subspecs => ["GrowingIO"]
#  pod 'iOSDFULibrary'
  commonPods
end





