# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
workspace 'Hello_Swift.xcworkspace'

#xcodeproj 'SwiftNote_App/SwiftNote_App.xcodeproj'
use_frameworks!

def commonPods
         #UI library
         pod 'SnapKit'
         pod 'FilesProvider'
         pod 'SwiftyJSON'
         pod 'FLAnimatedImage'
         pod 'MJRefresh'
end

target 'SwiftTest_App' do
  project 'SwiftTest_App/SwiftTest_App.xcodeproj'
  
  # 网络检测
  pod 'Reachability'
  pod 'Alamofire', :inhibit_warnings => true #网络处理
  pod 'ctc_podspec', :git =>'https://github.com/chuntiancai/TestCocoapod.git' #测试自己制作的cocoapod库
  
  # 测试绘制图表第三方库
  pod 'Charts' , '~>3.6.0'
  
  # 集成bugly，上报bug
  pod 'Bugly'
  
  # 测试图片下载的第三方库
  pod 'SDWebImage','~>5.11.1'
  
  #测试日历显示的第三方库
  pod 'FSCalendar','~>2.8.2'
  
  commonPods
  
end

target 'SwiftNote_App' do
  project 'SwiftNote_App/SwiftNote_App.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  # 网络检测
  pod 'Reachability'
  commonPods
  
end

target 'SwiftBluetooth_App' do
  project 'SwiftBluetooth_App/SwiftBluetooth_App.xcodeproj'
#  pod 'iOSDFULibrary'
  commonPods
end





